<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1735828560885' stop='1735828565121'>
    <name>API Testing: GET APIs</name>
    <title>API Testing: GET APIs</title>
    <test-cases>
        <test-case start='1735828560886' status='broken' stop='1735828561619'>
            <name>Should fetch all books successfully for admin</name>
            <title>Should fetch all books successfully for admin</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>`cy.request()` failed trying to load:
                
                http://localhost:7081/api/books
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ECONNREFUSED 127.0.0.1:7081
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: GET
                URL: http://localhost:7081/api/books
                
                -----------------------------------------------------------
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                https://on.cypress.io/request</message>
                <stack-trace>CypressError: `cy.request()` failed trying to load:
                
                http://localhost:7081/api/books
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ECONNREFUSED 127.0.0.1:7081
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: GET
                URL: http://localhost:7081/api/books
                
                -----------------------------------------------------------
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                https://on.cypress.io/request
                    at &lt;unknown> (http://localhost:60771/__cypress/runner/cypress_runner.js:132904:70)
                    at tryCatcher (http://localhost:60771/__cypress/runner/cypress_runner.js:1830:23)
                    at &lt;unknown> (http://localhost:60771/__cypress/runner/cypress_runner.js:4226:37)
                    at tryCatcher (http://localhost:60771/__cypress/runner/cypress_runner.js:1830:23)
                    at Promise._settlePromiseFromHandler (http://localhost:60771/__cypress/runner/cypress_runner.js:1542:31)
                    at Promise._settlePromise (http://localhost:60771/__cypress/runner/cypress_runner.js:1599:18)
                    at Promise._settlePromise0 (http://localhost:60771/__cypress/runner/cypress_runner.js:1644:10)
                    at Promise._settlePromises (http://localhost:60771/__cypress/runner/cypress_runner.js:1720:18)
                    at _drainQueueStep (http://localhost:60771/__cypress/runner/cypress_runner.js:2430:12)
                    at _drainQueue (http://localhost:60771/__cypress/runner/cypress_runner.js:2423:9)
                    at Async._drainQueues (http://localhost:60771/__cypress/runner/cypress_runner.js:2439:5)
                    at Async.drainQueues (http://localhost:60771/__cypress/runner/cypress_runner.js:2309:14)
                From Your Spec Code:
                    at Context.eval (http://localhost:60771/__cypress/tests?p=cypress\integration\api\books\get.cy.js:8:10)
                
                From Node.js Internals:
                  RequestError: Error: connect ECONNREFUSED 127.0.0.1:7081
                      at new r (&lt;embedded>:227:405020)
                      at ee.callback (&lt;embedded>:227:411021)
                      at e.callback.s.callback [as _callback] (&lt;embedded>:227:410467)
                      at s._callback.s.callback.s.callback (&lt;embedded>:290:100275)
                      at ee.emit (node:events:514:28)
                      at ee.onRequestError (&lt;embedded>:290:109217)
                      at ClientRequest.emit (node:events:526:35)
                      at Socket.socketErrorListener (node:_http_client:501:9)
                      at Socket.emit (node:events:514:28)
                      at emitErrorNT (node:internal/streams/destroy:151:8)
                      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1735828561639' status='broken' stop='1735828562318'>
            <name>Should fetch a specific book by ID successfully for admin</name>
            <title>Should fetch a specific book by ID successfully for admin</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>`cy.request()` failed trying to load:
                
                http://localhost:7081/api/books/3
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ECONNREFUSED 127.0.0.1:7081
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: GET
                URL: http://localhost:7081/api/books/3
                
                -----------------------------------------------------------
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                https://on.cypress.io/request</message>
                <stack-trace>CypressError: `cy.request()` failed trying to load:
                
                http://localhost:7081/api/books/3
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ECONNREFUSED 127.0.0.1:7081
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: GET
                URL: http://localhost:7081/api/books/3
                
                -----------------------------------------------------------
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                https://on.cypress.io/request
                    at &lt;unknown> (http://localhost:60771/__cypress/runner/cypress_runner.js:132904:70)
                    at tryCatcher (http://localhost:60771/__cypress/runner/cypress_runner.js:1830:23)
                    at &lt;unknown> (http://localhost:60771/__cypress/runner/cypress_runner.js:4226:37)
                    at tryCatcher (http://localhost:60771/__cypress/runner/cypress_runner.js:1830:23)
                    at Promise._settlePromiseFromHandler (http://localhost:60771/__cypress/runner/cypress_runner.js:1542:31)
                    at Promise._settlePromise (http://localhost:60771/__cypress/runner/cypress_runner.js:1599:18)
                    at Promise._settlePromise0 (http://localhost:60771/__cypress/runner/cypress_runner.js:1644:10)
                    at Promise._settlePromises (http://localhost:60771/__cypress/runner/cypress_runner.js:1720:18)
                    at _drainQueueStep (http://localhost:60771/__cypress/runner/cypress_runner.js:2430:12)
                    at _drainQueue (http://localhost:60771/__cypress/runner/cypress_runner.js:2423:9)
                    at Async._drainQueues (http://localhost:60771/__cypress/runner/cypress_runner.js:2439:5)
                    at Async.drainQueues (http://localhost:60771/__cypress/runner/cypress_runner.js:2309:14)
                From Your Spec Code:
                    at Context.eval (http://localhost:60771/__cypress/tests?p=cypress\integration\api\books\get.cy.js:20:10)
                
                From Node.js Internals:
                  RequestError: Error: connect ECONNREFUSED 127.0.0.1:7081
                      at new r (&lt;embedded>:227:405020)
                      at ee.callback (&lt;embedded>:227:411021)
                      at e.callback.s.callback [as _callback] (&lt;embedded>:227:410467)
                      at s._callback.s.callback.s.callback (&lt;embedded>:290:100275)
                      at ee.emit (node:events:514:28)
                      at ee.onRequestError (&lt;embedded>:290:109217)
                      at ClientRequest.emit (node:events:526:35)
                      at Socket.socketErrorListener (node:_http_client:501:9)
                      at Socket.emit (node:events:514:28)
                      at emitErrorNT (node:internal/streams/destroy:151:8)
                      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1735828562331' status='broken' stop='1735828563027'>
            <name>Should return 404 for a non-existing book ID for admin</name>
            <title>Should return 404 for a non-existing book ID for admin</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>`cy.request()` failed trying to load:
                
                http://localhost:7081/api/books/999
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ECONNREFUSED 127.0.0.1:7081
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: GET
                URL: http://localhost:7081/api/books/999
                
                -----------------------------------------------------------
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                https://on.cypress.io/request</message>
                <stack-trace>CypressError: `cy.request()` failed trying to load:
                
                http://localhost:7081/api/books/999
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ECONNREFUSED 127.0.0.1:7081
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: GET
                URL: http://localhost:7081/api/books/999
                
                -----------------------------------------------------------
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                https://on.cypress.io/request
                    at &lt;unknown> (http://localhost:60771/__cypress/runner/cypress_runner.js:132904:70)
                    at tryCatcher (http://localhost:60771/__cypress/runner/cypress_runner.js:1830:23)
                    at &lt;unknown> (http://localhost:60771/__cypress/runner/cypress_runner.js:4226:37)
                    at tryCatcher (http://localhost:60771/__cypress/runner/cypress_runner.js:1830:23)
                    at Promise._settlePromiseFromHandler (http://localhost:60771/__cypress/runner/cypress_runner.js:1542:31)
                    at Promise._settlePromise (http://localhost:60771/__cypress/runner/cypress_runner.js:1599:18)
                    at Promise._settlePromise0 (http://localhost:60771/__cypress/runner/cypress_runner.js:1644:10)
                    at Promise._settlePromises (http://localhost:60771/__cypress/runner/cypress_runner.js:1720:18)
                    at _drainQueueStep (http://localhost:60771/__cypress/runner/cypress_runner.js:2430:12)
                    at _drainQueue (http://localhost:60771/__cypress/runner/cypress_runner.js:2423:9)
                    at Async._drainQueues (http://localhost:60771/__cypress/runner/cypress_runner.js:2439:5)
                    at Async.drainQueues (http://localhost:60771/__cypress/runner/cypress_runner.js:2309:14)
                From Your Spec Code:
                    at Context.eval (http://localhost:60771/__cypress/tests?p=cypress\integration\api\books\get.cy.js:34:10)
                
                From Node.js Internals:
                  RequestError: Error: connect ECONNREFUSED 127.0.0.1:7081
                      at new r (&lt;embedded>:227:405020)
                      at ee.callback (&lt;embedded>:227:411021)
                      at e.callback.s.callback [as _callback] (&lt;embedded>:227:410467)
                      at s._callback.s.callback.s.callback (&lt;embedded>:290:100275)
                      at ee.emit (node:events:514:28)
                      at ee.onRequestError (&lt;embedded>:290:109217)
                      at ClientRequest.emit (node:events:526:35)
                      at Socket.socketErrorListener (node:_http_client:501:9)
                      at Socket.emit (node:events:514:28)
                      at emitErrorNT (node:internal/streams/destroy:151:8)
                      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1735828563040' status='broken' stop='1735828563719'>
            <name>Should fetch all books successfully for user</name>
            <title>Should fetch all books successfully for user</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>`cy.request()` failed trying to load:
                
                http://localhost:7081/api/books
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ECONNREFUSED 127.0.0.1:7081
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: GET
                URL: http://localhost:7081/api/books
                
                -----------------------------------------------------------
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                https://on.cypress.io/request</message>
                <stack-trace>CypressError: `cy.request()` failed trying to load:
                
                http://localhost:7081/api/books
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ECONNREFUSED 127.0.0.1:7081
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: GET
                URL: http://localhost:7081/api/books
                
                -----------------------------------------------------------
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                https://on.cypress.io/request
                    at &lt;unknown> (http://localhost:60771/__cypress/runner/cypress_runner.js:132904:70)
                    at tryCatcher (http://localhost:60771/__cypress/runner/cypress_runner.js:1830:23)
                    at &lt;unknown> (http://localhost:60771/__cypress/runner/cypress_runner.js:4226:37)
                    at tryCatcher (http://localhost:60771/__cypress/runner/cypress_runner.js:1830:23)
                    at Promise._settlePromiseFromHandler (http://localhost:60771/__cypress/runner/cypress_runner.js:1542:31)
                    at Promise._settlePromise (http://localhost:60771/__cypress/runner/cypress_runner.js:1599:18)
                    at Promise._settlePromise0 (http://localhost:60771/__cypress/runner/cypress_runner.js:1644:10)
                    at Promise._settlePromises (http://localhost:60771/__cypress/runner/cypress_runner.js:1720:18)
                    at _drainQueueStep (http://localhost:60771/__cypress/runner/cypress_runner.js:2430:12)
                    at _drainQueue (http://localhost:60771/__cypress/runner/cypress_runner.js:2423:9)
                    at Async._drainQueues (http://localhost:60771/__cypress/runner/cypress_runner.js:2439:5)
                    at Async.drainQueues (http://localhost:60771/__cypress/runner/cypress_runner.js:2309:14)
                From Your Spec Code:
                    at Context.eval (http://localhost:60771/__cypress/tests?p=cypress\integration\api\books\get.cy.js:47:10)
                
                From Node.js Internals:
                  RequestError: Error: connect ECONNREFUSED 127.0.0.1:7081
                      at new r (&lt;embedded>:227:405020)
                      at ee.callback (&lt;embedded>:227:411021)
                      at e.callback.s.callback [as _callback] (&lt;embedded>:227:410467)
                      at s._callback.s.callback.s.callback (&lt;embedded>:290:100275)
                      at ee.emit (node:events:514:28)
                      at ee.onRequestError (&lt;embedded>:290:109217)
                      at ClientRequest.emit (node:events:526:35)
                      at Socket.socketErrorListener (node:_http_client:501:9)
                      at Socket.emit (node:events:514:28)
                      at emitErrorNT (node:internal/streams/destroy:151:8)
                      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1735828563732' status='broken' stop='1735828564416'>
            <name>Should fetch a specific book by ID successfully for user</name>
            <title>Should fetch a specific book by ID successfully for user</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>`cy.request()` failed trying to load:
                
                http://localhost:7081/api/books/3
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ECONNREFUSED 127.0.0.1:7081
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: GET
                URL: http://localhost:7081/api/books/3
                
                -----------------------------------------------------------
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                https://on.cypress.io/request</message>
                <stack-trace>CypressError: `cy.request()` failed trying to load:
                
                http://localhost:7081/api/books/3
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ECONNREFUSED 127.0.0.1:7081
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: GET
                URL: http://localhost:7081/api/books/3
                
                -----------------------------------------------------------
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                https://on.cypress.io/request
                    at &lt;unknown> (http://localhost:60771/__cypress/runner/cypress_runner.js:132904:70)
                    at tryCatcher (http://localhost:60771/__cypress/runner/cypress_runner.js:1830:23)
                    at &lt;unknown> (http://localhost:60771/__cypress/runner/cypress_runner.js:4226:37)
                    at tryCatcher (http://localhost:60771/__cypress/runner/cypress_runner.js:1830:23)
                    at Promise._settlePromiseFromHandler (http://localhost:60771/__cypress/runner/cypress_runner.js:1542:31)
                    at Promise._settlePromise (http://localhost:60771/__cypress/runner/cypress_runner.js:1599:18)
                    at Promise._settlePromise0 (http://localhost:60771/__cypress/runner/cypress_runner.js:1644:10)
                    at Promise._settlePromises (http://localhost:60771/__cypress/runner/cypress_runner.js:1720:18)
                    at _drainQueueStep (http://localhost:60771/__cypress/runner/cypress_runner.js:2430:12)
                    at _drainQueue (http://localhost:60771/__cypress/runner/cypress_runner.js:2423:9)
                    at Async._drainQueues (http://localhost:60771/__cypress/runner/cypress_runner.js:2439:5)
                    at Async.drainQueues (http://localhost:60771/__cypress/runner/cypress_runner.js:2309:14)
                From Your Spec Code:
                    at Context.eval (http://localhost:60771/__cypress/tests?p=cypress\integration\api\books\get.cy.js:59:10)
                
                From Node.js Internals:
                  RequestError: Error: connect ECONNREFUSED 127.0.0.1:7081
                      at new r (&lt;embedded>:227:405020)
                      at ee.callback (&lt;embedded>:227:411021)
                      at e.callback.s.callback [as _callback] (&lt;embedded>:227:410467)
                      at s._callback.s.callback.s.callback (&lt;embedded>:290:100275)
                      at ee.emit (node:events:514:28)
                      at ee.onRequestError (&lt;embedded>:290:109217)
                      at ClientRequest.emit (node:events:526:35)
                      at Socket.socketErrorListener (node:_http_client:501:9)
                      at Socket.emit (node:events:514:28)
                      at emitErrorNT (node:internal/streams/destroy:151:8)
                      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1735828564428' status='broken' stop='1735828565117'>
            <name>Should return 404 for a non-existing book ID for user</name>
            <title>Should return 404 for a non-existing book ID for user</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>`cy.request()` failed trying to load:
                
                http://localhost:7081/api/books/999
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ECONNREFUSED 127.0.0.1:7081
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: GET
                URL: http://localhost:7081/api/books/999
                
                -----------------------------------------------------------
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                https://on.cypress.io/request</message>
                <stack-trace>CypressError: `cy.request()` failed trying to load:
                
                http://localhost:7081/api/books/999
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ECONNREFUSED 127.0.0.1:7081
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: GET
                URL: http://localhost:7081/api/books/999
                
                -----------------------------------------------------------
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                https://on.cypress.io/request
                    at &lt;unknown> (http://localhost:60771/__cypress/runner/cypress_runner.js:132904:70)
                    at tryCatcher (http://localhost:60771/__cypress/runner/cypress_runner.js:1830:23)
                    at &lt;unknown> (http://localhost:60771/__cypress/runner/cypress_runner.js:4226:37)
                    at tryCatcher (http://localhost:60771/__cypress/runner/cypress_runner.js:1830:23)
                    at Promise._settlePromiseFromHandler (http://localhost:60771/__cypress/runner/cypress_runner.js:1542:31)
                    at Promise._settlePromise (http://localhost:60771/__cypress/runner/cypress_runner.js:1599:18)
                    at Promise._settlePromise0 (http://localhost:60771/__cypress/runner/cypress_runner.js:1644:10)
                    at Promise._settlePromises (http://localhost:60771/__cypress/runner/cypress_runner.js:1720:18)
                    at _drainQueueStep (http://localhost:60771/__cypress/runner/cypress_runner.js:2430:12)
                    at _drainQueue (http://localhost:60771/__cypress/runner/cypress_runner.js:2423:9)
                    at Async._drainQueues (http://localhost:60771/__cypress/runner/cypress_runner.js:2439:5)
                    at Async.drainQueues (http://localhost:60771/__cypress/runner/cypress_runner.js:2309:14)
                From Your Spec Code:
                    at Context.eval (http://localhost:60771/__cypress/tests?p=cypress\integration\api\books\get.cy.js:73:10)
                
                From Node.js Internals:
                  RequestError: Error: connect ECONNREFUSED 127.0.0.1:7081
                      at new r (&lt;embedded>:227:405020)
                      at ee.callback (&lt;embedded>:227:411021)
                      at e.callback.s.callback [as _callback] (&lt;embedded>:227:410467)
                      at s._callback.s.callback.s.callback (&lt;embedded>:290:100275)
                      at ee.emit (node:events:514:28)
                      at ee.onRequestError (&lt;embedded>:290:109217)
                      at ClientRequest.emit (node:events:526:35)
                      at Socket.socketErrorListener (node:_http_client:501:9)
                      at Socket.emit (node:events:514:28)
                      at emitErrorNT (node:internal/streams/destroy:151:8)
                      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>